#pragma once

#define DAC_SAMPLE_MAX 1023U

#ifdef AUDIO_ENABLE
  #define STARTUP_SONG SONG(ZELDA_CHEST)
#endif

#define MUSIC_MASK (keycode != KC_NO)

#define MIDI_BASIC

#define MOUSEKEY_DELAY 300
#define MOUSEKEY_INTERVAL 50
#define MOUSEKEY_MAX_SPEED 8
#define MOUSEKEY_TIME_TO_MAX 20
